export const ActionTypes = {
    SET_ALL_ROOMS :"SET_ALL_ROOMS",
    CURRENT_ROOM:"CURRENT_ROOM",
    SELECTED_ROOM : "SELECTED_ROOM",
    REMOVE_SELECTED_ROOM : "REMOVE_SELECTED_ROOM",
    SET_USER:"SET_USER",
    UPDATE_TALK:"UPDATE_TALK"
}